# database configuration
spring.datasource.disjob:
  driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc-url: jdbc:mysql://localhost:3306/disjob?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&connectTimeout=2000&socketTimeout=5000&serverTimezone=Asia/Shanghai&failOverReadOnly=false
  username: disjob
  password: disjob$123456
  minimum-idle: 10
  maximum-pool-size: 200
  connection-timeout: 2000
  pool-name: disjob
  #connection-test-query: SELECT 1    # jdbc4不建议配置connectionTestQuery
