# Disjob worker configuration
disjob.worker:
  group: default
  timing-wheel-tick-ms: 100
  timing-wheel-ring-size: 60
  maximum-pool-size: 100
  keep-alive-time-seconds: 300
  process-thread-pool-size: 6
