# redis configuration
spring.redis:
  database: 0
  host: localhost       # redis standalone host name
  port: 6379            # redis standalone port
  #username: test_redis  # redis node auth username
  password: 123456       # redis node auth password
  connect-timeout: 3000
  timeout: 5000
  #sentinel:
  #  master: REDIS_SENTINEL
  #  nodes: 112.74.170.75:16379,112.74.170.75:16380
    #username: test_sentinel # redis sentinel auth username
    #password: 654321        # redis sentinel auth password
  client-type: LETTUCE
  lettuce:
    pool:
      max-active: 32
      max-idle: 8
      min-idle: 4
      max-wait: 5000
    shutdown-timeout: 5000

disjob.registry.redis:
  namespace: redis_namespace
  session-timeout-ms: 60000
  registry-period-ms: 4000
