logging.config: classpath:log4j2.xml

# actuator monitor configuration
management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    enabled-by-default: true
  info:
    env:
      enabled: true

# disable thymeleaf configuration
spring.thymeleaf:
  check-template: false
  check-template-location: false

# “swagger-ui” and “/api-docs endpoint” custom path
springdoc:
  swagger-ui:
    path: /docs.html
    layout: StandaloneLayout
  api-docs.path: /docs

# tomcat server configuration
server.tomcat:
  threads:
    max: 500
    min-spare: 20
  accept-count: 200
  max-connections: 20000
  mbeanregistry.enabled: true

# Disjob supervisor configuration
disjob.http:
  connect-timeout: 2000
  read-timeout: 5000
  max-retry-times: 3
