logging.config: classpath:log4j2.xml

# actuator monitor configuration
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

# “swagger-ui” and “/api-docs endpoint” custom path
springdoc:
  swagger-ui:
    path: /docs.html
    layout: StandaloneLayout
  api-docs.path: /docs

# tomcat server configuration
server.tomcat:
  threads:
    max: 500
    min-spare: 20
  accept-count: 200
  max-connections: 20000
  mbeanregistry.enabled: true

# Disjob supervisor configuration
disjob.http:
  connect-timeout: 2000
  read-timeout: 5000
  max-retry-times: 3
